# -*- coding: utf-8 -*-
"""Deputados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wByNScNDTChYB-Itt1uhYXgDxPy68nkY
"""

# Install dependencies
!pip3 install -q numpy scipy
!pip3 install --upgrade -q gspread

#Subir Arquivo
from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv

sns.set(style="whitegrid")
# %matplotlib inline

deputados = pd.read_csv('Ano-2018.csv',sep=';',encoding='utf-8',quoting=csv.QUOTE_NONE)

#visualizar valores 
#deputados.shape
#deputados.columns
#deputados.info()

#Convertendo campos para valores
deputados['vlrGlosa'] = deputados['vlrGlosa'].str.replace(',','.').astype('float')
deputados['vlrDocumento'] = deputados['vlrDocumento'].str.replace(',','.').astype('float')
deputados['vlrLiquido'] = deputados['vlrLiquido'].str.replace(',','.').astype('float')
deputados['txtCNPJCPF'] = deputados['txtCNPJCPF'].astype(str)

#visualizar dados faltantes
#plt.figure(figsize=(15,5))
#sns.heatmap(deputados.isnull(), yticklabels=False, cbar=False, cmap='viridis')


#COntar
#deputados['txNomeParlamentar'].nunique()

"""
#Grafico por estado 
n_dep = pd.DataFrame(deputados.groupby('sgUF')['txNomeParlamentar'].nunique())
plt.figure(figsize=(15,5))
x = sns.barplot(x=n_dep.index,y='txNomeParlamentar', data=n_dep)
x.set(xlabel = 'Estados', ylabel = 'Números de Deputados')
"""

#total geral
soma_total = round(sum(deputados['vlrLiquido']),2)
soma_total

#Por tipo de gasto 
gastos_por_desc=pd.DataFrame(deputados.groupby('txtDescricao')['vlrLiquido'].sum())
gastos_por_desc.sort_values('vlrLiquido',ascending=False, inplace=True)
gastos_por_desc['vlrLiquido']=round(gastos_por_desc['vlrLiquido'],2)
gastos_por_desc['%'] = round(gastos_por_desc['vlrLiquido'] / soma_total  * 100,2)
gastos_por_desc

#Por tipo de palarmentar 
gastos_por_dep=pd.DataFrame(deputados.groupby('txNomeParlamentar')['vlrLiquido'].sum())
gastos_por_dep.sort_values('vlrLiquido',ascending=False, inplace=True)
gastos_por_dep['vlrLiquido']=round(gastos_por_dep['vlrLiquido'],2)
gastos_por_dep['%'] = round(gastos_por_dep['vlrLiquido'] / soma_total  * 100,2)
gastos_por_dep


#deputados.columns